Alocohol dehydrogenation:
    config:
        a:
            initial_value: 2
            lower: 1
            unit: dimensionless
            upper: 3
            value: 2
    equation: ethanol * a
    reaction: r0
LoadEnzymeML:
    path: Test.omex
ParameterEstimation:
    thinlayer: copasi
